### ISSUE TITLE
ability to setup aliases

### ISSUE THREAD

**Issue by chrisdrackett** [remorses/bundless#2]
I'm trying to get vitro working with a react-native-web project and I'm having issues figuring out how to alias `react-native` to `react-native-web` seems like ideally I should have a way to set this up and I think it might need to happen in this package.

**Comment by remorses** [comment]
This is now possible using the alias plugin


```ts
// bundless.config.js
const { AliasPlugin } = require('@bundless/plugin-alias')

module.exports = {
    plugins: [
        AliasPlugin({
            entries: { react: 'preact/compat' },
        }),
    ],
}
```


To use this in vitro you will need to pass it to `bundlessConfig.plugins`
